"""Curated content for Tasbih.ai · Ginan, Dua, Family/ECDC.

All content is presented as **reflective**, not authoritative. Translations and
paraphrases are gentle and personal; Tasbih.ai is not a religious authority.

Credits: curated by Naushad & Shabnam Patel · Andheri Jamatkhana · Mumbai · India.

You can replace, add, or remove any item below — the backend reads this module
on startup and exposes the lists via:
  GET  /api/ginan
  GET  /api/ginan/{id}
  GET  /api/dua
  GET  /api/dua/{id}
  GET  /api/family-corner
"""

# Each Ginan: id, title (Gujarati/transliterated), pir (attributed author),
#             gujarati (script), transliteration, english (gentle paraphrase),
#             theme (one of: love, light, journey, surrender, service, remembrance)
GINAN: list[dict] = [
    {
        "id": "eji_dhan_dhan_aaj",
        "title": "Eji Dhan Dhan Aaj no Dahaaḍo",
        "pir": "Pir Hasan Kabirdin",
        "gujarati": "એ જી ધન ધન આજ નો દિવસ\nમૂળ માલિક ઘેર આવ્યા",
        "transliteration": "Eji dhan dhan aaj no dahaaḍo\nMūl mālik ghar āvyā",
        "english": "How blessed this day — the Lord of all has come home. Sit still; whatever you were carrying, set it down.",
        "theme": "remembrance",
    },
    {
        "id": "eji_ya_ali_khūb_majālas",
        "title": "Eji Yā ʿAlī Khūb Majālas",
        "pir": "Pir Sadardin",
        "gujarati": "એ જી યા અલી ખૂબ મજાલસ\nદીદાર દિયો મુજ રે",
        "transliteration": "Eji Yā ʿAlī khūb majālas\nDīdār diyo muj re",
        "english": "Yā ʿAlī — in this beautiful gathering, please grant me a glimpse. Even a flicker is enough to last a year.",
        "theme": "love",
    },
    {
        "id": "eji_aap_baandhī_chalo",
        "title": "Eji Āp Bāndhī Chalo",
        "pir": "Pir Shams",
        "gujarati": "એ જી આપ બાંધી ચાલો\nરસ્તો સોપાનો છે",
        "transliteration": "Eji āp bāndhī chālo\nRasto sopāno chhe",
        "english": "Keep yourself gathered as you walk — the path is a staircase, climbed one quiet step at a time.",
        "theme": "journey",
    },
    {
        "id": "eji_sahebjī_tum_rahim",
        "title": "Eji Sāhebji Tum Rahīm",
        "pir": "Pir Hasan Kabirdin",
        "gujarati": "એ જી સાહેબજી તુમ રહીમ\nદયા કરો રે પ્રીતમ",
        "transliteration": "Eji Sāhebji tum rahīm\nDayā karo re prītam",
        "english": "Beloved — you are merciful. Please be gentle with me. I am small, and the day is long.",
        "theme": "surrender",
    },
    {
        "id": "eji_navroz_no_din",
        "title": "Eji Navroz No Din",
        "pir": "Pir Sadardin",
        "gujarati": "એ જી નવરોઝ નો દિન સોહામણો\nઆવ્યો રે પ્રીતમ",
        "transliteration": "Eji Navroz no din sohāmaṇo\nĀvyo re prītam",
        "english": "Beautiful is the day of Navroz — beloved, you have arrived. Set one calm intention; the year will hold it.",
        "theme": "remembrance",
    },
    {
        "id": "eji_īmān_kā_dīpak",
        "title": "Eji Īmān Kā Dīpak",
        "pir": "Pir Shams",
        "gujarati": "એ જી ઈમાન કા દીપક\nદિલ માહિ બળે",
        "transliteration": "Eji īmān kā dīpak\nDil māhī bale",
        "english": "The lamp of faith burns inside the heart. Tend to it — gently, without showing off — and it will last the night.",
        "theme": "light",
    },
    {
        "id": "eji_seva_karo_re_bhāī",
        "title": "Eji Seva Karo Re Bhāī",
        "pir": "Pir Hasan Kabirdin",
        "gujarati": "એ જી સેવા કરો રે ભાઈ\nનિરમલ ભાવ થી",
        "transliteration": "Eji seva karo re bhāī\nNirmal bhāv thī",
        "english": "Serve, my friend — with a clean heart. Not for credit, not for praise. Just because the world is gentler when you do.",
        "theme": "service",
    },
    {
        "id": "eji_man_re_chalo",
        "title": "Eji Man Re Chālo",
        "pir": "Pir Sadardin",
        "gujarati": "એ જી મન રે ચાલો\nમૂળ મંજિલ રાહ",
        "transliteration": "Eji man re chālo\nMūl manzil rāh",
        "english": "Heart, walk on — the path back to the source is open. The road is quiet; you are not alone.",
        "theme": "journey",
    },
    {
        "id": "eji_satgur_milyā",
        "title": "Eji Satgur Milyā",
        "pir": "Pir Shams",
        "gujarati": "એ જી સતગુર મિલ્યા\nભવ સાગર પાર",
        "transliteration": "Eji satgur milyā\nBhav sāgar pār",
        "english": "I have met the true guide — and across the ocean of life, I can finally rest a moment.",
        "theme": "surrender",
    },
    {
        "id": "eji_aakhā_jāmā_māhī",
        "title": "Eji Ākhā Jāmā Māhī",
        "pir": "Pir Hasan Kabirdin",
        "gujarati": "એ જી આખા જમા માહી\nનૂર સોહામણો",
        "transliteration": "Eji ākhā jāmā māhī\nNūr sohāmaṇo",
        "english": "Within the whole jamat — a beautiful light is shining. Look around this hall; every face is part of it.",
        "theme": "light",
    },
    {
        "id": "eji_chalo_chalo_re_man",
        "title": "Eji Chālo Chālo Re Man",
        "pir": "Pir Sadardin",
        "gujarati": "એ જી ચાલો ચાલો રે મન\nરાહ ગુરુ નો",
        "transliteration": "Eji chālo chālo re man\nRāh guru no",
        "english": "Come on, come on, my heart — the guide's path is waiting. Take the first step before the courage cools.",
        "theme": "journey",
    },
    {
        "id": "eji_prabhu_tum_dīpak",
        "title": "Eji Prabhu Tum Dīpak",
        "pir": "Pir Shams",
        "gujarati": "એ જી પ્રભુ તુમ દીપક\nહું પતંગ",
        "transliteration": "Eji prabhu tum dīpak\nHun patang",
        "english": "Beloved, you are the flame and I am the moth — drawn always to the warmth, even when it costs me everything.",
        "theme": "love",
    },
]

# Holy Du'a — recited three times a day by the Shia Ismaili Muslim Jamat.
# Each verse below is one swipe-card in the Instagram-style Dua page.
# Structure: six rakaats. Each card carries rakaat (1-6), order, transliteration
# (primary, large), english (gentle rendering), arabic (revealed on tap),
# and a short title that orients the soul before the words arrive.
# Imam reference updated to Shah Rahim al-Husayni (Aga Khan V).
DUA: list[dict] = [
    # ── Rakaat 1 ─────────────────────────────────────────────────────
    {
        "id": "r1_01_bismillah",
        "rakaat": 1, "order": 1, "situation": "rakaat-1",
        "title": "In the Name",
        "transliteration": "Bismillāhir-Rahmānir-Raheem",
        "english": "In the name of Allah, the most Beneficent, the most Merciful.",
        "arabic": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    },
    {
        "id": "r1_02_alhamd",
        "rakaat": 1, "order": 2, "situation": "rakaat-1",
        "title": "All Praise",
        "transliteration": "Al-hamdu lillāhi Rabbil 'Ālameen",
        "english": "All praise is due to Allah, the Lord of the worlds.",
        "arabic": "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    },
    {
        "id": "r1_03_rahman",
        "rakaat": 1, "order": 3, "situation": "rakaat-1",
        "title": "The Beneficent",
        "transliteration": "Ar-Rahmānir-Raheem",
        "english": "The most Beneficent, the most Merciful.",
        "arabic": "الرَّحْمَٰنِ الرَّحِيمِ",
    },
    {
        "id": "r1_04_maalik",
        "rakaat": 1, "order": 4, "situation": "rakaat-1",
        "title": "The Day of Judgment",
        "transliteration": "Māliki Yawmid-Deen",
        "english": "The Lord of the Day of Judgment.",
        "arabic": "مَالِكِ يَوْمِ الدِّينِ",
    },
    {
        "id": "r1_05_iyyaka",
        "rakaat": 1, "order": 5, "situation": "rakaat-1",
        "title": "You Alone",
        "transliteration": "Iyyāka na'budu wa iyyāka nasta'een",
        "english": "You alone we worship and You alone we seek for help.",
        "arabic": "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
    },
    {
        "id": "r1_06_ihdina",
        "rakaat": 1, "order": 6, "situation": "rakaat-1",
        "title": "Guide Us",
        "transliteration": "Ihdinas-Sirātal Mustaqeem",
        "english": "Guide us to the right path.",
        "arabic": "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
    },
    {
        "id": "r1_07_sirat_anam",
        "rakaat": 1, "order": 7, "situation": "rakaat-1",
        "title": "Path of the Favoured",
        "transliteration": "Sirātal-lazeena an'amta 'alayhim",
        "english": "The path of those upon whom You have bestowed favours.",
        "arabic": "صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ",
    },
    {
        "id": "r1_08_ghair",
        "rakaat": 1, "order": 8, "situation": "rakaat-1",
        "title": "Not Astray",
        "transliteration": "Ghairil maghdūbi 'alayhim walad-dāl-leen",
        "english": "Not of those who incurred wrath, nor of those who have gone astray.",
        "arabic": "غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ",
    },
    {
        "id": "r1_09_sajada",
        "rakaat": 1, "order": 9, "situation": "rakaat-1",
        "title": "I Prostrate",
        "transliteration": "Sajada wajhī ilayka",
        "english": "I prostrate before You.",
        "arabic": "سَجَدَ وَجْهِي إِلَيْكَ",
    },
    {
        "id": "r1_10_tawakkal",
        "rakaat": 1, "order": 10, "situation": "rakaat-1",
        "title": "I Rely",
        "transliteration": "Wa tawakkaltu 'alayka",
        "english": "And I rely upon You.",
        "arabic": "وَتَوَكَّلْتُ عَلَيْكَ",
    },
    {
        "id": "r1_11_quwwati",
        "rakaat": 1, "order": 11, "situation": "rakaat-1",
        "title": "My Strength",
        "transliteration": "Minka quwwatī",
        "english": "From You is my strength.",
        "arabic": "مِنْكَ قُوَّتِي",
    },
    {
        "id": "r1_12_ismati",
        "rakaat": 1, "order": 12, "situation": "rakaat-1",
        "title": "My Protection",
        "transliteration": "Wa anta 'ismatī",
        "english": "And You are my protection.",
        "arabic": "وَأَنْتَ عِصْمَتِي",
    },
    {
        "id": "r1_13_ya_rabb",
        "rakaat": 1, "order": 13, "situation": "rakaat-1",
        "title": "O Lord of the Worlds",
        "transliteration": "Yā Rabbal 'Ālameen",
        "english": "O Lord of the worlds.",
        "arabic": "يَا رَبَّ الْعَالَمِينَ",
    },
    {
        "id": "r1_14_salli_muhammad",
        "rakaat": 1, "order": 14, "situation": "rakaat-1",
        "title": "Peace on the Chosen",
        "transliteration": "Allāhumma salli 'alā Muhammadinil-Mustafā",
        "english": "O Allah, let Your peace be on Muhammad — the Chosen.",
        "arabic": "اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ الْمُصْطَفَىٰ",
    },
    {
        "id": "r1_15_aly_murtaza",
        "rakaat": 1, "order": 15, "situation": "rakaat-1",
        "title": "And on Aly",
        "transliteration": "Wa 'alā 'Aliyyinil Murtazā",
        "english": "And on Aly — the Favourite.",
        "arabic": "وَعَلَىٰ عَلِيٍّ الْمُرْتَضَىٰ",
    },
    {
        "id": "r1_16_aimma",
        "rakaat": 1, "order": 16, "situation": "rakaat-1",
        "title": "And the Imams",
        "transliteration": "Wa 'alal A'immatil At'hār",
        "english": "And on the Imams — the Pure.",
        "arabic": "وَعَلَى الْأَئِمَّةِ الْأَطْهَارِ",
    },
    {
        "id": "r1_17_hujjah",
        "rakaat": 1, "order": 17, "situation": "rakaat-1",
        "title": "The Proof",
        "transliteration": "Wa 'alā Hujjatil Amr",
        "english": "And on the evidence of Your Authority.",
        "arabic": "وَعَلَىٰ حُجَّةِ الْأَمْرِ",
    },
    {
        "id": "r1_18_sahib_zaman",
        "rakaat": 1, "order": 18, "situation": "rakaat-1",
        "title": "Lord of the Age",
        "transliteration": "Sāhibiz-zamāni wal 'asr",
        "english": "The Lord of the age and the time.",
        "arabic": "صَاحِبِ الزَّمَانِ وَالْعَصْرِ",
    },
    {
        "id": "r1_19_hazir",
        "rakaat": 1, "order": 19, "situation": "rakaat-1",
        "title": "Present, Living",
        "transliteration": "Imāminal Hāziril Mawjood",
        "english": "Our present, living Imam.",
        "arabic": "إِمَامِنَا الْحَاضِرِ الْمَوْجُودِ",
    },
    {
        "id": "r1_20_shah_rahim",
        "rakaat": 1, "order": 20, "situation": "rakaat-1",
        "title": "Mawlana Shah Rahim",
        "transliteration": "Mawlānā Shāh Rahimil Husaynī",
        "english": "Our Lord Shah Rahim al-Husayni.",
        "arabic": "مَوْلَانَا شَاهْ رَحِيمِ الْحُسَيْنِي",
    },
    {
        "id": "r1_21_sujoodi",
        "rakaat": 1, "order": 21, "situation": "rakaat-1",
        "title": "My Prostration (×4)",
        "transliteration": "Allāhumma laka sujoodī wa tā-'atī",
        "english": "O Allah, to You is my prostration and obedience. (recited four times)",
        "arabic": "اللَّهُمَّ لَكَ سُجُودِي وَطَاعَتِي",
        "repeat": 4,
    },

    # ── Rakaat 2 ─────────────────────────────────────────────────────
    {
        "id": "r2_01_bismillah",
        "rakaat": 2, "order": 1, "situation": "rakaat-2",
        "title": "In the Name",
        "transliteration": "Bismillāhir-Rahmānir-Raheem",
        "english": "In the name of Allah, the most Beneficent, the most Merciful.",
        "arabic": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    },
    {
        "id": "r2_02_ya_ayyuhal",
        "rakaat": 2, "order": 2, "situation": "rakaat-2",
        "title": "O Believers",
        "transliteration": "Yā ayyuhal-lazeena āmanū",
        "english": "O you who believe!",
        "arabic": "يَا أَيُّهَا الَّذِينَ آمَنُوا",
    },
    {
        "id": "r2_03_ati_allah",
        "rakaat": 2, "order": 3, "situation": "rakaat-2",
        "title": "Obey",
        "transliteration": "Ati'ullāha wa ati'ur-Rasūla",
        "english": "Obey Allah and obey the Apostle.",
        "arabic": "أَطِيعُوا اللَّهَ وَأَطِيعُوا الرَّسُولَ",
    },
    {
        "id": "r2_04_ulil_amr",
        "rakaat": 2, "order": 4, "situation": "rakaat-2",
        "title": "Holders of Authority",
        "transliteration": "Wa ulil amri minkum",
        "english": "And the holders of authority from amongst you.",
        "arabic": "وَأُولِي الْأَمْرِ مِنْكُمْ",
    },
    {
        "id": "r2_05_imam_mubeen",
        "rakaat": 2, "order": 5, "situation": "rakaat-2",
        "title": "Vested in the Imam",
        "transliteration": "Wa kulla shai'in ahsainahu fī Imāmim-Mubeen",
        "english": "And We have vested everything in the manifest Imam.",
        "arabic": "وَكُلَّ شَيْءٍ أَحْصَيْنَاهُ فِي إِمَامٍ مُبِينٍ",
    },
    {
        "id": "r2_06_ya_mawlana",
        "rakaat": 2, "order": 6, "situation": "rakaat-2",
        "title": "O Our Lord",
        "transliteration": "Allāhumma yā Mawlānā",
        "english": "O Allah, O our Lord.",
        "arabic": "اللَّهُمَّ يَا مَوْلَانَا",
    },
    {
        "id": "r2_07_anta_salaam",
        "rakaat": 2, "order": 7, "situation": "rakaat-2",
        "title": "You Are Peace",
        "transliteration": "Antas-Salām",
        "english": "You are the peace.",
        "arabic": "أَنْتَ السَّلَامُ",
    },
    {
        "id": "r2_08_minka_salaam",
        "rakaat": 2, "order": 8, "situation": "rakaat-2",
        "title": "From You, Peace",
        "transliteration": "Wa minkas-Salām",
        "english": "And from You is the peace.",
        "arabic": "وَمِنْكَ السَّلَامُ",
    },
    {
        "id": "r2_09_ilayka_salaam",
        "rakaat": 2, "order": 9, "situation": "rakaat-2",
        "title": "To You, Peace Returns",
        "transliteration": "Wa ilayka yarji'us-Salām",
        "english": "And to You returns the peace.",
        "arabic": "وَإِلَيْكَ يَرْجِعُ السَّلَامُ",
    },
    {
        "id": "r2_10_hayyina",
        "rakaat": 2, "order": 10, "situation": "rakaat-2",
        "title": "A Life of Peace",
        "transliteration": "Hayyinā Rabbanā bis-Salām",
        "english": "O our Lord, grant us a life of peace.",
        "arabic": "حَيِّنَا رَبَّنَا بِالسَّلَامِ",
    },
    {
        "id": "r2_11_daras_salaam",
        "rakaat": 2, "order": 11, "situation": "rakaat-2",
        "title": "The Abode of Peace",
        "transliteration": "Wa adkhilnā dāras-Salām",
        "english": "And usher us into the abode of peace.",
        "arabic": "وَأَدْخِلْنَا دَارَ السَّلَامِ",
    },
    {
        "id": "r2_12_tabarakta",
        "rakaat": 2, "order": 12, "situation": "rakaat-2",
        "title": "Blessed Are You",
        "transliteration": "Tabārakta Rabbanā wa ta'ālayta",
        "english": "Blessed are You, our Lord, the most High.",
        "arabic": "تَبَارَكْتَ رَبَّنَا وَتَعَالَيْتَ",
    },
    {
        "id": "r2_13_jalal",
        "rakaat": 2, "order": 13, "situation": "rakaat-2",
        "title": "Majesty & Reverence",
        "transliteration": "Yā Zal Jalāli wal Ikrām",
        "english": "O Lord of Majesty and Reverence.",
        "arabic": "يَا ذَا الْجَلَالِ وَالْإِكْرَامِ",
    },
    {
        "id": "r2_14_madadi",
        "rakaat": 2, "order": 14, "situation": "rakaat-2",
        "title": "My Help",
        "transliteration": "Allāhumma yā Mawlānā minka madadī",
        "english": "O Allah, our Lord, from You is my help.",
        "arabic": "اللَّهُمَّ يَا مَوْلَانَا مِنْكَ مَدَدِي",
    },
    {
        "id": "r2_15_mutamad",
        "rakaat": 2, "order": 15, "situation": "rakaat-2",
        "title": "My Reliance",
        "transliteration": "Wa 'alayka mu'tamadī",
        "english": "And upon You is my reliance.",
        "arabic": "وَعَلَيْكَ مُعْتَمَدِي",
    },
    {
        "id": "r2_16_iyyaka_2",
        "rakaat": 2, "order": 16, "situation": "rakaat-2",
        "title": "You Alone",
        "transliteration": "Iyyāka na'budu wa iyyāka nasta'een",
        "english": "You alone we worship and You alone we seek for help.",
        "arabic": "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ",
    },
    {
        "id": "r2_17_ya_aly_lutfika",
        "rakaat": 2, "order": 17, "situation": "rakaat-2",
        "title": "Help Me, O Aly",
        "transliteration": "Yā 'Aly bi-lutfika adriknī",
        "english": "O Aly, help me with Your kindness.",
        "arabic": "يَا عَلِيُّ بِلُطْفِكَ أَدْرِكْنِي",
    },
    {
        "id": "r2_18_shahada_1",
        "rakaat": 2, "order": 18, "situation": "rakaat-2",
        "title": "There Is No Deity",
        "transliteration": "Lā ilāha illā-llāh",
        "english": "There is no deity except Allah.",
        "arabic": "لَا إِلَٰهَ إِلَّا اللَّهُ",
    },
    {
        "id": "r2_19_shahada_2",
        "rakaat": 2, "order": 19, "situation": "rakaat-2",
        "title": "Muhammad, the Messenger",
        "transliteration": "Muhammadur-Rasūlullāh",
        "english": "Muhammad is the Messenger of Allah.",
        "arabic": "مُحَمَّدٌ رَسُولُ اللَّهِ",
    },
    {
        "id": "r2_20_aly_ameer",
        "rakaat": 2, "order": 20, "situation": "rakaat-2",
        "title": "Aly, the Master",
        "transliteration": "'Aliyyun Amīrul-Mu'mineena 'Aliyyullāh",
        "english": "Aly — the master of believers — is from Allah.",
        "arabic": "عَلِيٌّ أَمِيرُ الْمُؤْمِنِينَ عَلِيٌّ وَلِيُّ اللَّهِ",
    },
    {
        "id": "r2_21_shah_rahim",
        "rakaat": 2, "order": 21, "situation": "rakaat-2",
        "title": "Mawlana Shah Rahim",
        "transliteration": "Mawlānā Shāh Rahimul Husaynī",
        "english": "Our Lord Shah Rahim al-Husayni.",
        "arabic": "مَوْلَانَا شَاهْ رَحِيمُ الْحُسَيْنِي",
    },
    {
        "id": "r2_22_imam_hazir",
        "rakaat": 2, "order": 22, "situation": "rakaat-2",
        "title": "Present, Living Imam",
        "transliteration": "Al-Imāmul Hāzirul Mawjood",
        "english": "The present, living Imam.",
        "arabic": "الْإِمَامُ الْحَاضِرُ الْمَوْجُودُ",
    },
    {
        "id": "r2_23_sujoodi",
        "rakaat": 2, "order": 23, "situation": "rakaat-2",
        "title": "My Prostration",
        "transliteration": "Allāhumma laka sujoodī wa tā-'atī",
        "english": "O Allah, to You is my prostration and obedience.",
        "arabic": "اللَّهُمَّ لَكَ سُجُودِي وَطَاعَتِي",
        "repeat": 4,
    },

    # ── Rakaat 3 ─────────────────────────────────────────────────────
    {
        "id": "r3_01_bismillah",
        "rakaat": 3, "order": 1, "situation": "rakaat-3",
        "title": "In the Name",
        "transliteration": "Bismillāhir-Rahmānir-Raheem",
        "english": "In the name of Allah, the most Beneficent, the most Merciful.",
        "arabic": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    },
    {
        "id": "r3_02_balligh",
        "rakaat": 3, "order": 2, "situation": "rakaat-3",
        "title": "O Apostle, Deliver",
        "transliteration": "Yā ayyuhar-Rasūlu balligh",
        "english": "O Apostle, deliver (to the people)...",
        "arabic": "يَا أَيُّهَا الرَّسُولُ بَلِّغْ",
    },
    {
        "id": "r3_03_unzila",
        "rakaat": 3, "order": 3, "situation": "rakaat-3",
        "title": "What Was Revealed",
        "transliteration": "Mā unzila ilayka mir-Rabbika",
        "english": "What has been revealed to you from your Lord.",
        "arabic": "مَا أُنْزِلَ إِلَيْكَ مِنْ رَبِّكَ",
    },
    {
        "id": "r3_04_illam_tafal",
        "rakaat": 3, "order": 4, "situation": "rakaat-3",
        "title": "If You Did Not",
        "transliteration": "Wa il-lam taf'al",
        "english": "And if you did not do so...",
        "arabic": "وَإِنْ لَمْ تَفْعَلْ",
    },
    {
        "id": "r3_05_balaghta",
        "rakaat": 3, "order": 5, "situation": "rakaat-3",
        "title": "Not Delivered",
        "transliteration": "Famā ballaghta risālatah",
        "english": "Then you have not delivered His Message.",
        "arabic": "فَمَا بَلَّغْتَ رِسَالَتَهُ",
    },
    {
        "id": "r3_06_yasimuka",
        "rakaat": 3, "order": 6, "situation": "rakaat-3",
        "title": "Allah Will Protect",
        "transliteration": "Wallāhu ya'simuka minan-nās",
        "english": "And Allah will protect you from the people.",
        "arabic": "وَاللَّهُ يَعْصِمُكَ مِنَ النَّاسِ",
    },
    {
        "id": "r3_07_hayy",
        "rakaat": 3, "order": 7, "situation": "rakaat-3",
        "title": "The Ever-Living",
        "transliteration": "Lā ilāha illā-llāhul Hayyul Qayyoom",
        "english": "There is no deity except Allah, the Ever-Living, the Eternal.",
        "arabic": "لَا إِلَٰهَ إِلَّا اللَّهُ الْحَيُّ الْقَيُّومُ",
    },
    {
        "id": "r3_08_haqq_mubeen",
        "rakaat": 3, "order": 8, "situation": "rakaat-3",
        "title": "The Evident Truth",
        "transliteration": "Lā ilāha illā-llāhul Malikul Haqqul Mubeen",
        "english": "There is no deity except Allah, the Sovereign, the Ultimate Truth, the Evident.",
        "arabic": "لَا إِلَٰهَ إِلَّا اللَّهُ الْمَلِكُ الْحَقُّ الْمُبِينُ",
    },
    {
        "id": "r3_09_haqq_yaqeen",
        "rakaat": 3, "order": 9, "situation": "rakaat-3",
        "title": "The Certain Truth",
        "transliteration": "Lā ilāha illā-llāhul Malikul Haqqul Yaqeen",
        "english": "There is no deity except Allah, the Sovereign, the Ultimate Truth, the Certainty.",
        "arabic": "لَا إِلَٰهَ إِلَّا اللَّهُ الْمَلِكُ الْحَقُّ الْيَقِينُ",
    },
    {
        "id": "r3_10_maliku_yaum",
        "rakaat": 3, "order": 10, "situation": "rakaat-3",
        "title": "Lord of the Day",
        "transliteration": "Lā ilāha illā-llāhu Māliku Yawmid-Deen",
        "english": "There is no deity except Allah, the Lord of the Day of Judgment.",
        "arabic": "لَا إِلَٰهَ إِلَّا اللَّهُ مَالِكُ يَوْمِ الدِّينِ",
    },
    {
        "id": "r3_11_la_fata",
        "rakaat": 3, "order": 11, "situation": "rakaat-3",
        "title": "No Hero Like Aly",
        "transliteration": "Lā fatā illā 'Aly",
        "english": "There is no hero except Aly.",
        "arabic": "لَا فَتَىٰ إِلَّا عَلِيٌّ",
    },
    {
        "id": "r3_12_zulfiqar",
        "rakaat": 3, "order": 12, "situation": "rakaat-3",
        "title": "No Sword Like Zulfiqar",
        "transliteration": "Lā saifa illā Zulfiqār",
        "english": "There is no sword except (his sword) 'Zulfiqar'.",
        "arabic": "لَا سَيْفَ إِلَّا ذُو الْفِقَارِ",
    },
    {
        "id": "r3_13_tawassal",
        "rakaat": 3, "order": 13, "situation": "rakaat-3",
        "title": "Seek the Help",
        "transliteration": "Tawassalū 'indal masā'ib",
        "english": "Seek, at the time of difficulties, the help...",
        "arabic": "تَوَسَّلُوا عِنْدَ الْمَصَائِبِ",
    },
    {
        "id": "r3_14_bi_mawlakum",
        "rakaat": 3, "order": 14, "situation": "rakaat-3",
        "title": "Through Your Lord",
        "transliteration": "Bi Mawlākumil Hāziril Mawjood",
        "english": "Of your Lord, the present, living Imam.",
        "arabic": "بِمَوْلَاكُمُ الْحَاضِرِ الْمَوْجُودِ",
    },
    {
        "id": "r3_15_shah_rahim",
        "rakaat": 3, "order": 15, "situation": "rakaat-3",
        "title": "Shah Rahim al-Husayni",
        "transliteration": "Shāh Rahimil Husaynī",
        "english": "Shah Rahim al-Husayni.",
        "arabic": "شَاهْ رَحِيمِ الْحُسَيْنِي",
    },
    {
        "id": "r3_16_sujoodi",
        "rakaat": 3, "order": 16, "situation": "rakaat-3",
        "title": "My Prostration",
        "transliteration": "Allāhumma laka sujoodī wa tā-'atī",
        "english": "O Allah, to You is my prostration and obedience.",
        "arabic": "اللَّهُمَّ لَكَ سُجُودِي وَطَاعَتِي",
        "repeat": 4,
    },

    # ── Rakaat 4 ─────────────────────────────────────────────────────
    {
        "id": "r4_01_bismillah",
        "rakaat": 4, "order": 1, "situation": "rakaat-4",
        "title": "In the Name",
        "transliteration": "Bismillāhir-Rahmānir-Raheem",
        "english": "In the name of Allah, the most Beneficent, the most Merciful.",
        "arabic": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    },
    {
        "id": "r4_02_innal_lazeena",
        "rakaat": 4, "order": 2, "situation": "rakaat-4",
        "title": "Those Who Pledge",
        "transliteration": "Innal-lazeena yubāyi'ūnaka",
        "english": "Verily, those who give you their allegiance...",
        "arabic": "إِنَّ الَّذِينَ يُبَايِعُونَكَ",
    },
    {
        "id": "r4_03_innama_yubayiun",
        "rakaat": 4, "order": 3, "situation": "rakaat-4",
        "title": "Allegiance to Allah",
        "transliteration": "Innamā yubāyi'ūnallāh",
        "english": "They give it but to Allah (Himself).",
        "arabic": "إِنَّمَا يُبَايِعُونَ اللَّهَ",
    },
    {
        "id": "r4_04_yadullah",
        "rakaat": 4, "order": 4, "situation": "rakaat-4",
        "title": "The Hand of Allah",
        "transliteration": "Yadullāhi fawqa aydeehim",
        "english": "Allah's hand is upon their hands.",
        "arabic": "يَدُ اللَّهِ فَوْقَ أَيْدِيهِمْ",
    },
    {
        "id": "r4_05_fa_man_nakatha",
        "rakaat": 4, "order": 5, "situation": "rakaat-4",
        "title": "He Who Breaks",
        "transliteration": "Faman-nakatha",
        "english": "Then he who breaks it...",
        "arabic": "فَمَنْ نَكَثَ",
    },
    {
        "id": "r4_06_yankuth",
        "rakaat": 4, "order": 6, "situation": "rakaat-4",
        "title": "Against Himself",
        "transliteration": "Fa innamā yankuthu 'alā nafsih",
        "english": "He certainly breaks it against himself.",
        "arabic": "فَإِنَّمَا يَنْكُثُ عَلَىٰ نَفْسِهِ",
    },
    {
        "id": "r4_07_wa_man_aufa",
        "rakaat": 4, "order": 7, "situation": "rakaat-4",
        "title": "He Who Fulfils",
        "transliteration": "Wa man awfā",
        "english": "And he who fulfils...",
        "arabic": "وَمَنْ أَوْفَىٰ",
    },
    {
        "id": "r4_08_bima_ahad",
        "rakaat": 4, "order": 8, "situation": "rakaat-4",
        "title": "The Pledge with Allah",
        "transliteration": "Bimā 'āhada 'alayhullāha",
        "english": "What he has pledged with Allah.",
        "arabic": "بِمَا عَاهَدَ عَلَيْهُ اللَّهَ",
    },
    {
        "id": "r4_09_ajran_azeem",
        "rakaat": 4, "order": 9, "situation": "rakaat-4",
        "title": "A Great Reward",
        "transliteration": "Fasayu'tīhi ajran 'azeemā",
        "english": "He shall in return reward him in plenty.",
        "arabic": "فَسَيُؤْتِيهِ أَجْرًا عَظِيمًا",
    },
    {
        "id": "r4_10_allahummaghfir",
        "rakaat": 4, "order": 10, "situation": "rakaat-4",
        "title": "Forgive Our Sins",
        "transliteration": "Allāhummaghfir lanā zunoobanā",
        "english": "O Allah, forgive us our sins.",
        "arabic": "اللَّهُمَّ اغْفِرْ لَنَا ذُنُوبَنَا",
    },
    {
        "id": "r4_11_warzuqna",
        "rakaat": 4, "order": 11, "situation": "rakaat-4",
        "title": "Sustenance & Mercy",
        "transliteration": "Warzuqnā warhamnā",
        "english": "Give us our daily bread, and have mercy upon us.",
        "arabic": "وَارْزُقْنَا وَارْحَمْنَا",
    },
    {
        "id": "r4_12_haqqi_rusul",
        "rakaat": 4, "order": 12, "situation": "rakaat-4",
        "title": "Your Close Messengers",
        "transliteration": "Bi haqqi rusulikal muqarrabeen",
        "english": "In the name of Your closest Messengers.",
        "arabic": "بِحَقِّ رُسُلِكَ الْمُقَرَّبِينَ",
    },
    {
        "id": "r4_13_aimma_tahareen",
        "rakaat": 4, "order": 13, "situation": "rakaat-4",
        "title": "Your Holy Imams",
        "transliteration": "Wa A'immatikal Mutahhareen",
        "english": "And Your holy Imams.",
        "arabic": "وَأَئِمَّتِكَ الْمُطَهَّرِينَ",
    },
    {
        "id": "r4_14_haqqi_mawlana",
        "rakaat": 4, "order": 14, "situation": "rakaat-4",
        "title": "In the Name of Our Lord",
        "transliteration": "Wa bi haqqi Mawlānā",
        "english": "And in the name of our Lord.",
        "arabic": "وَبِحَقِّ مَوْلَانَا",
    },
    {
        "id": "r4_15_shah_rahim",
        "rakaat": 4, "order": 15, "situation": "rakaat-4",
        "title": "Imam Shah Rahim",
        "transliteration": "Wa Imāminā Shāh Rahimil Husaynī",
        "english": "And our Imam, Shah Rahim al-Husayni.",
        "arabic": "وَإِمَامِنَا شَاهْ رَحِيمِ الْحُسَيْنِي",
    },
    {
        "id": "r4_16_sujoodi",
        "rakaat": 4, "order": 16, "situation": "rakaat-4",
        "title": "My Prostration",
        "transliteration": "Allāhumma laka sujoodī wa tā-'atī",
        "english": "O Allah, to You is my prostration and obedience.",
        "arabic": "اللَّهُمَّ لَكَ سُجُودِي وَطَاعَتِي",
        "repeat": 4,
    },

    # ── Rakaat 5 ─────────────────────────────────────────────────────
    {
        "id": "r5_01_bismillah",
        "rakaat": 5, "order": 1, "situation": "rakaat-5",
        "title": "In the Name",
        "transliteration": "Bismillāhir-Rahmānir-Raheem",
        "english": "In the name of Allah, the most Beneficent, the most Merciful.",
        "arabic": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    },
    {
        "id": "r5_02_ya_ayyuhal",
        "rakaat": 5, "order": 2, "situation": "rakaat-5",
        "title": "O Believers",
        "transliteration": "Yā ayyuhal-lazeena āmanū",
        "english": "O you who believe!",
        "arabic": "يَا أَيُّهَا الَّذِينَ آمَنُوا",
    },
    {
        "id": "r5_03_takhoonu",
        "rakaat": 5, "order": 3, "situation": "rakaat-5",
        "title": "Do Not Betray",
        "transliteration": "Lā takhoonullāha war-Rasūla",
        "english": "Do not betray Allah and the Apostle.",
        "arabic": "لَا تَخُونُوا اللَّهَ وَالرَّسُولَ",
    },
    {
        "id": "r5_04_amanat",
        "rakaat": 5, "order": 4, "situation": "rakaat-5",
        "title": "Your Trusts",
        "transliteration": "Wa takhoonū amānātikum",
        "english": "And (do not) betray your trusts.",
        "arabic": "وَتَخُونُوا أَمَانَاتِكُمْ",
    },
    {
        "id": "r5_05_talamoon",
        "rakaat": 5, "order": 5, "situation": "rakaat-5",
        "title": "While You Know",
        "transliteration": "Wa antum ta'lamoon",
        "english": "While you know.",
        "arabic": "وَأَنْتُمْ تَعْلَمُونَ",
    },
    {
        "id": "r5_06_rabbanaghfir",
        "rakaat": 5, "order": 6, "situation": "rakaat-5",
        "title": "Forgive Us",
        "transliteration": "Rabbanaghfir lanā zunoobanā",
        "english": "O our Lord, forgive us our sins.",
        "arabic": "رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا",
    },
    {
        "id": "r5_07_sahhil",
        "rakaat": 5, "order": 7, "situation": "rakaat-5",
        "title": "Ease Our Tasks",
        "transliteration": "Wa sah-hil umooranā",
        "english": "And make our tasks easy.",
        "arabic": "وَسَهِّلْ أُمُورَنَا",
    },
    {
        "id": "r5_08_warzuqna",
        "rakaat": 5, "order": 8, "situation": "rakaat-5",
        "title": "Sustenance & Mercy",
        "transliteration": "Warzuqnā warhamnā",
        "english": "Give us our daily bread, and have mercy upon us.",
        "arabic": "وَارْزُقْنَا وَارْحَمْنَا",
    },
    {
        "id": "r5_09_qadeer",
        "rakaat": 5, "order": 9, "situation": "rakaat-5",
        "title": "The Omnipotent",
        "transliteration": "Innaka 'alā kulli shay'in qadeer",
        "english": "Verily, You are the Omnipotent.",
        "arabic": "إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
        "mid_insert": {
            "kind": "verse",
            "title": "A whispered call",
            "transliteration": "Yā 'Aly yā Muhammad — yā Muhammad yā 'Aly",
            "english": "O Aly, O Muhammad — O Muhammad, O Aly.",
            "arabic": "يَا عَلِيُّ يَا مُحَمَّد · يَا مُحَمَّد يَا عَلِيُّ",
        },
    },
    {
        "id": "r5_10_imam_zaman",
        "rakaat": 5, "order": 10, "situation": "rakaat-5",
        "title": "O Imam of the Time",
        "transliteration": "Yā Imāmaz-Zamān, yā Mawlānā",
        "english": "O Imam of the time, O our Lord.",
        "arabic": "يَا إِمَامَ الزَّمَانِ يَا مَوْلَانَا",
    },
    {
        "id": "r5_11_anta_quwwati",
        "rakaat": 5, "order": 11, "situation": "rakaat-5",
        "title": "You Are My Strength",
        "transliteration": "Anta quwwatī",
        "english": "You are my strength.",
        "arabic": "أَنْتَ قُوَّتِي",
    },
    {
        "id": "r5_12_anta_sanadi",
        "rakaat": 5, "order": 12, "situation": "rakaat-5",
        "title": "You Are My Support",
        "transliteration": "Wa anta sanadī",
        "english": "And You are my support.",
        "arabic": "وَأَنْتَ سَنَدِي",
    },
    {
        "id": "r5_13_tikali",
        "rakaat": 5, "order": 13, "situation": "rakaat-5",
        "title": "On You I Rely",
        "transliteration": "Wa 'alayka ittikālī",
        "english": "And on You I rely.",
        "arabic": "وَعَلَيْكَ اتِّكَالِي",
    },
    {
        "id": "r5_14_ya_hazir",
        "rakaat": 5, "order": 14, "situation": "rakaat-5",
        "title": "O Present, Living",
        "transliteration": "Yā Hāzir yā Mawjood",
        "english": "O present, O living.",
        "arabic": "يَا حَاضِرُ يَا مَوْجُودُ",
    },
    {
        "id": "r5_15_ya_shah_rahim",
        "rakaat": 5, "order": 15, "situation": "rakaat-5",
        "title": "O Shah Rahim",
        "transliteration": "Yā Shāh Rahimul Husaynī",
        "english": "O Shah Rahim al-Husayni.",
        "arabic": "يَا شَاهْ رَحِيمُ الْحُسَيْنِي",
    },
    {
        "id": "r5_16_antal_imam",
        "rakaat": 5, "order": 16, "situation": "rakaat-5",
        "title": "The True Manifest Imam",
        "transliteration": "Antal Imāmul Haqqul Mubeen",
        "english": "You are the true, manifest Imam.",
        "arabic": "أَنْتَ الْإِمَامُ الْحَقُّ الْمُبِينُ",
    },

    # ── Rakaat 6 ─────────────────────────────────────────────────────
    {
        "id": "r6_01_bismillah",
        "rakaat": 6, "order": 1, "situation": "rakaat-6",
        "title": "In the Name",
        "transliteration": "Bismillāhir-Rahmānir-Raheem",
        "english": "In the name of Allah, the most Beneficent, the most Merciful.",
        "arabic": "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    },
    {
        "id": "r6_02_qul_huwallah",
        "rakaat": 6, "order": 2, "situation": "rakaat-6",
        "title": "Allah, the One",
        "transliteration": "Qul Huwallāhu Ahad",
        "english": "Say: it is Allah, (Who is) the One.",
        "arabic": "قُلْ هُوَ اللَّهُ أَحَدٌ",
    },
    {
        "id": "r6_03_samad",
        "rakaat": 6, "order": 3, "situation": "rakaat-6",
        "title": "The Absolute",
        "transliteration": "Allāhus-Samad",
        "english": "Allah is Absolute, Independent.",
        "arabic": "اللَّهُ الصَّمَدُ",
    },
    {
        "id": "r6_04_lam_yalid",
        "rakaat": 6, "order": 4, "situation": "rakaat-6",
        "title": "He Did Not Beget",
        "transliteration": "Lam yalid",
        "english": "He did not beget.",
        "arabic": "لَمْ يَلِدْ",
    },
    {
        "id": "r6_05_lam_yulad",
        "rakaat": 6, "order": 5, "situation": "rakaat-6",
        "title": "Nor Was He Begotten",
        "transliteration": "Wa lam yūlad",
        "english": "Nor was He begotten.",
        "arabic": "وَلَمْ يُولَدْ",
    },
    {
        "id": "r6_06_kufuwan",
        "rakaat": 6, "order": 6, "situation": "rakaat-6",
        "title": "None Like Him",
        "transliteration": "Wa lam yakullahū kufuwan ahad",
        "english": "And there is none like unto Him.",
        "arabic": "وَلَمْ يَكُنْ لَهُ كُفُوًا أَحَدٌ",
    },
    {
        "id": "r6_07_bi_haqqi_muhammad",
        "rakaat": 6, "order": 7, "situation": "rakaat-6",
        "title": "In the Name of Muhammad",
        "transliteration": "Allāhumma bi haqqi Muhammadinil-Mustafā",
        "english": "O Allah, in the name of Muhammad — the Chosen.",
        "arabic": "اللَّهُمَّ بِحَقِّ مُحَمَّدٍ الْمُصْطَفَىٰ",
    },
    {
        "id": "r6_08_aly_murtaza",
        "rakaat": 6, "order": 8, "situation": "rakaat-6",
        "title": "And Aly the Favourite",
        "transliteration": "Wa 'Aliyyinil-Murtazā",
        "english": "And Aly — the Favourite.",
        "arabic": "وَعَلِيٍّ الْمُرْتَضَىٰ",
    },
    {
        "id": "r6_09_fatima",
        "rakaat": 6, "order": 9, "situation": "rakaat-6",
        "title": "Fatima the Radiant",
        "transliteration": "Wa Fātimataz-Zahrā",
        "english": "And Fatima — the Radiant.",
        "arabic": "وَفَاطِمَةَ الزَّهْرَاءِ",
    },
    {
        "id": "r6_10_hasan_husayn",
        "rakaat": 6, "order": 10, "situation": "rakaat-6",
        "title": "Hasan & Husayn",
        "transliteration": "Wal Hasani wal Husayn",
        "english": "And (Hazrat) Hasan, and (Imam) Husayn.",
        "arabic": "وَالْحَسَنِ وَالْحُسَيْنِ",
    },
    {
        "id": "r6_11_mawlana_aly",
        "rakaat": 6, "order": 11, "situation": "rakaat-6",
        "title": "Mawlana Aly",
        "transliteration": "Allāhumma bi haqqi Mawlānā 'Aly",
        "english": "O Allah, in the name of our Lord Aly.",
        "arabic": "اللَّهُمَّ بِحَقِّ مَوْلَانَا عَلِيٍّ",
        "interlude_after": {
            "kind": "imam_list",
            "id": "tasbih_imams",
            "title": "Tasbih of the Imams",
            "subtitle": "From Mawlana 'Aly to Noor Mawlana Shah Rahim al-Husayni",
            "english": "Fifty names — the unbroken chain of light, from the first to the present.",
            "names": [
                "Mawlana 'Aly",
                "Mawlana Husayn",
                "Mawlana Zain al-Abidin",
                "Mawlana Muhammad al-Baqir",
                "Mawlana Ja'far al-Sadiq",
                "Mawlana Isma'il",
                "Mawlana Muhammad ibn Isma'il",
                "Mawlana Wafi Ahmad",
                "Mawlana Taqi Muhammad",
                "Mawlana Radi al-Din Abdullah",
                "Mawlana Muhammad al-Mahdi",
                "Mawlana Qa'im",
                "Mawlana Mansur",
                "Mawlana Mu'izz",
                "Mawlana Aziz",
                "Mawlana al-Hakim bi-Amr Allah",
                "Mawlana Zaher",
                "Mawlana al-Mustansir Billah",
                "Mawlana Nizar",
                "Mawlana Hadi",
                "Mawlana Muhtadi",
                "Mawlana Qahir",
                "Mawlana Hasan Al-Zikr al-Salam",
                "Mawlana A'la Muhammad",
                "Mawlana Jalal al-Din Hasan",
                "Mawlana Ala al-Din Muhammad",
                "Mawlana Rukn al-Din Khurshah",
                "Mawlana Shams al-Din Muhammad",
                "Mawlana Qasim Shah",
                "Mawlana Islam Shah",
                "Mawlana Muhammad ibn Islam Shah",
                "Mawlana al-Mustansir Billah",
                "Mawlana Abd al-Salam",
                "Mawlana Gharib Mirza",
                "Mawlana Abi al-Dharr Ali",
                "Mawlana Murad Mirza",
                "Mawlana Zulfaqar Ali",
                "Mawlana Nur al-Din Ali",
                "Mawlana Khalil Allah Ali",
                "Mawlana Nizar",
                "Mawlana Sayyid Ali",
                "Mawlana Hasan Ali",
                "Mawlana Qasim Ali",
                "Mawlana Abu al-Hasan Ali",
                "Mawlana Khalil Allah Ali",
                "Mawlana Shah Hasan Ali",
                "Mawlana Shah Ali Shah",
                "Mawlana Sultan Muhammad Shah",
                "Mawlana Shah Karim al-Husayni",
                "Noor Mawlana Shah Rahim al-Husayni",
            ],
        },
    },
    {
        "id": "r6_12_mawlana_imam",
        "rakaat": 6, "order": 12, "situation": "rakaat-6",
        "title": "Our Lord & Imam",
        "transliteration": "Wa bi haqqi Mawlānā wa Imāminal Hāziril Mawjood",
        "english": "And in the name of our Lord and our present, living Imam.",
        "arabic": "وَبِحَقِّ مَوْلَانَا وَإِمَامِنَا الْحَاضِرِ الْمَوْجُودِ",
    },
    {
        "id": "r6_13_irhamna",
        "rakaat": 6, "order": 13, "situation": "rakaat-6",
        "title": "Have Mercy",
        "transliteration": "Shāh Rahimil Husaynī irhamnā",
        "english": "Shah Rahim al-Husayni, have mercy upon us.",
        "arabic": "شَاهْ رَحِيمِ الْحُسَيْنِي ارْحَمْنَا",
    },
    {
        "id": "r6_14_waghfir",
        "rakaat": 6, "order": 14, "situation": "rakaat-6",
        "title": "Forgive Us",
        "transliteration": "Waghfir lanā",
        "english": "And forgive us (our sins).",
        "arabic": "وَاغْفِرْ لَنَا",
        "mid_insert": {
            "kind": "verse",
            "title": "My Prostration",
            "transliteration": "Allāhumma laka sujoodī wa tā-'atī",
            "english": "O Allah, to You is my prostration and obedience.",
            "arabic": "اللَّهُمَّ لَكَ سُجُودِي وَطَاعَتِي",
        },
    },
    {
        "id": "r6_15_qadeer",
        "rakaat": 6, "order": 15, "situation": "rakaat-6",
        "title": "The Omnipotent",
        "transliteration": "Innaka 'alā kulli shay'in qadeer",
        "english": "Verily, You are the Omnipotent.",
        "arabic": "إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    },
    {
        "id": "r6_16_walhamdu",
        "rakaat": 6, "order": 16, "situation": "rakaat-6",
        "title": "All Praise",
        "transliteration": "Wal-hamdu lillāhi Rabbil 'Ālameen",
        "english": "And all praise is due to Allah, the Lord of the worlds.",
        "arabic": "وَالْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
    },
    {
        "id": "r6_17_shah_jo_didar",
        "rakaat": 6, "order": 17, "situation": "rakaat-6",
        "title": "Shāh jo Dīdār",
        "transliteration": "Shāh-jo-Dīdār",
        "english": "May you be blessed with the holy Dīdār of our Lord.",
        "arabic": "شَاهْ جو دِيدَار",
    },
    {
        "id": "r6_18_sujoodi",
        "rakaat": 6, "order": 18, "situation": "rakaat-6",
        "title": "My Prostration",
        "transliteration": "Allāhumma laka sujoodī wa tā-'atī",
        "english": "O Allah, to You is my prostration and obedience.",
        "arabic": "اللَّهُمَّ لَكَ سُجُودِي وَطَاعَتِي",
        "repeat": 4,
    },
]

# Family/ECDC — short reflective parenting prompts by age stage.
# Source: distilled from public-domain ECDC frameworks + Ismaili emphasis on
# pluralism, listening, and gentle parenting. Not clinical advice.
FAMILY_CORNER: list[dict] = [
    {
        "id": "infant_eye",
        "stage": "infant",   # 0-2
        "stage_label": "Infant · 0–2 yrs",
        "title": "An Unhurried Gaze",
        "prompt": "Sit with your baby. Look — really look — for one full minute. No phone, no song. Just your eyes and theirs. Notice what arrives in your chest.",
        "duration_min": 1,
    },
    {
        "id": "infant_name",
        "stage": "infant",
        "stage_label": "Infant · 0–2 yrs",
        "title": "Say Their Name Softly",
        "prompt": "Throughout today, say your child's name in the softest voice you can manage. Watch how they orient to it.",
        "duration_min": 5,
    },
    {
        "id": "infant_skin",
        "stage": "infant",
        "stage_label": "Infant · 0–2 yrs",
        "title": "Skin to Skin",
        "prompt": "For ten quiet minutes, hold your baby against your chest. Their heart will slow to match yours.",
        "duration_min": 10,
    },
    {
        "id": "toddler_choices",
        "stage": "toddler",  # 2-4
        "stage_label": "Toddler · 2–4 yrs",
        "title": "Two Small Choices",
        "prompt": "Offer your toddler two choices today instead of one instruction. \"Red cup or blue cup?\" The smallest agency builds the largest trust.",
        "duration_min": 3,
    },
    {
        "id": "toddler_emotion",
        "stage": "toddler",
        "stage_label": "Toddler · 2–4 yrs",
        "title": "Name the Feeling",
        "prompt": "When your toddler melts down, kneel to their height and say the feeling: \"You're frustrated. That's hard.\" Don't fix. Just name. Then sit with them.",
        "duration_min": 5,
    },
    {
        "id": "toddler_routine",
        "stage": "toddler",
        "stage_label": "Toddler · 2–4 yrs",
        "title": "One Sacred Routine",
        "prompt": "Pick one small ritual — a morning kiss, an evening lullaby, a particular hug at bedtime. Do it every day for a week. They will remember it for life.",
        "duration_min": 2,
    },
    {
        "id": "early_curiosity",
        "stage": "early",    # 4-7
        "stage_label": "Early childhood · 4–7 yrs",
        "title": "Honour One Question",
        "prompt": "Children at this age ask 'why?' hundreds of times. Pick one question today and answer it like it's the most important thing you'll do. Sit. Explain. Let them ask the next 'why'.",
        "duration_min": 8,
    },
    {
        "id": "early_storytime",
        "stage": "early",
        "stage_label": "Early childhood · 4–7 yrs",
        "title": "A Story Without a Lesson",
        "prompt": "Read a book at bedtime — not to teach a moral, just for the joy of words. Let them turn the pages. Don't rush.",
        "duration_min": 15,
    },
    {
        "id": "early_pluralism",
        "stage": "early",
        "stage_label": "Early childhood · 4–7 yrs",
        "title": "A Gentle First Pluralism",
        "prompt": "Tell your child about a friend or neighbour from a different faith or background. Use one calm sentence: 'Some people pray standing, some sitting, some quiet — all the prayers are heard.'",
        "duration_min": 4,
    },
    {
        "id": "middle_listening",
        "stage": "middle",   # 7-11
        "stage_label": "Middle childhood · 7–11 yrs",
        "title": "Three Quiet Minutes",
        "prompt": "Ask: 'How was your day?' Then wait. Don't fill the silence. Children of this age need permission to start. Three minutes of patience can unlock everything.",
        "duration_min": 3,
    },
    {
        "id": "middle_seva",
        "stage": "middle",
        "stage_label": "Middle childhood · 7–11 yrs",
        "title": "A Small Seva Together",
        "prompt": "Pick one small act of service — washing a neighbour's plate, sweeping a hallway, leaving a kind note. Do it side by side. No explanation needed.",
        "duration_min": 20,
    },
    {
        "id": "middle_emotion",
        "stage": "middle",
        "stage_label": "Middle childhood · 7–11 yrs",
        "title": "When They're Upset, Don't Fix",
        "prompt": "When your child is angry or sad, resist the urge to solve. Say: 'That sounds really hard. I'm here.' Stay. The lesson is that they are not alone in difficulty.",
        "duration_min": 10,
    },
    {
        "id": "adolescent_trust",
        "stage": "adolescent", # 11-15
        "stage_label": "Adolescent · 11–15 yrs",
        "title": "One Question, No Follow-up",
        "prompt": "Ask one curious question about their world today — a song, a meme, a friend. Don't interrogate. Listen. Tomorrow, ask again. Trust accumulates in small drops.",
        "duration_min": 5,
    },
    {
        "id": "adolescent_identity",
        "stage": "adolescent",
        "stage_label": "Adolescent · 11–15 yrs",
        "title": "Hold Identity Loosely",
        "prompt": "Your teen is becoming. Some days they will look like you; other days, very much not. Let them try on identities. The thread that matters — kindness — is the one you've been weaving for years.",
        "duration_min": 0,
    },
    {
        "id": "teen_phone",
        "stage": "teen",     # 15-18
        "stage_label": "Teen · 15–18 yrs",
        "title": "Phones Down at Dinner",
        "prompt": "One meal this week — no phones at the table. Yours included. The first 5 minutes may be awkward. Stay. The next 25 are the gift.",
        "duration_min": 30,
    },
    {
        "id": "teen_struggle",
        "stage": "teen",
        "stage_label": "Teen · 15–18 yrs",
        "title": "If They're Struggling",
        "prompt": "Teens often signal struggle by withdrawing, not asking. If you sense it: knock gently. Sit on the edge of the bed. Don't lecture. Say: 'I'm here. No agenda. Just here.'",
        "duration_min": 15,
    },
    {
        "id": "all_repair",
        "stage": "all",
        "stage_label": "Any age",
        "title": "Repair After Loss of Temper",
        "prompt": "You will lose your patience. Every parent does. Repair is the most powerful parenting move. Say: 'I shouted earlier. I was tired and that was not your fault. I'm sorry.' Then let it be.",
        "duration_min": 3,
    },
    {
        "id": "all_blessing",
        "stage": "all",
        "stage_label": "Any age",
        "title": "A Quiet Blessing at Night",
        "prompt": "After your child is asleep, sit by them for a moment. Whisper one gentle wish for them — your hope for who they become. They will not hear it. But you will.",
        "duration_min": 2,
    },
]
