"""Curated content for Tasbih.ai · Ginan, Dua, Family/ECDC.

All content is presented as **reflective**, not authoritative. Translations and
paraphrases are gentle and personal; Tasbih.ai is not a religious authority.

Credits: curated by Naushad & Shabnam Patel · Andheri Jamatkhana · Mumbai · India.

You can replace, add, or remove any item below — the backend reads this module
on startup and exposes the lists via:
  GET  /api/ginan
  GET  /api/ginan/{id}
  GET  /api/dua
  GET  /api/dua/{id}
  GET  /api/family-corner
"""

# Each Ginan: id, title (Gujarati/transliterated), pir (attributed author),
#             gujarati (script), transliteration, english (gentle paraphrase),
#             theme (one of: love, light, journey, surrender, service, remembrance)
GINAN: list[dict] = [
    {
        "id": "eji_dhan_dhan_aaj",
        "title": "Eji Dhan Dhan Aaj no Dahaaḍo",
        "pir": "Pir Hasan Kabirdin",
        "gujarati": "એ જી ધન ધન આજ નો દિવસ\nમૂળ માલિક ઘેર આવ્યા",
        "transliteration": "Eji dhan dhan aaj no dahaaḍo\nMūl mālik ghar āvyā",
        "english": "How blessed this day — the Lord of all has come home. Sit still; whatever you were carrying, set it down.",
        "theme": "remembrance",
    },
    {
        "id": "eji_ya_ali_khūb_majālas",
        "title": "Eji Yā ʿAlī Khūb Majālas",
        "pir": "Pir Sadardin",
        "gujarati": "એ જી યા અલી ખૂબ મજાલસ\nદીદાર દિયો મુજ રે",
        "transliteration": "Eji Yā ʿAlī khūb majālas\nDīdār diyo muj re",
        "english": "Yā ʿAlī — in this beautiful gathering, please grant me a glimpse. Even a flicker is enough to last a year.",
        "theme": "love",
    },
    {
        "id": "eji_aap_baandhī_chalo",
        "title": "Eji Āp Bāndhī Chalo",
        "pir": "Pir Shams",
        "gujarati": "એ જી આપ બાંધી ચાલો\nરસ્તો સોપાનો છે",
        "transliteration": "Eji āp bāndhī chālo\nRasto sopāno chhe",
        "english": "Keep yourself gathered as you walk — the path is a staircase, climbed one quiet step at a time.",
        "theme": "journey",
    },
    {
        "id": "eji_sahebjī_tum_kareem",
        "title": "Eji Sāhebji Tum Karīm",
        "pir": "Pir Hasan Kabirdin",
        "gujarati": "એ જી સાહેબજી તુમ કરીમ\nદયા કરો રે પ્રીતમ",
        "transliteration": "Eji Sāhebji tum karīm\nDayā karo re prītam",
        "english": "Beloved — you are generous. Please be merciful with me. I am small, and the day is long.",
        "theme": "surrender",
    },
    {
        "id": "eji_navroz_no_din",
        "title": "Eji Navroz No Din",
        "pir": "Pir Sadardin",
        "gujarati": "એ જી નવરોઝ નો દિન સોહામણો\nઆવ્યો રે પ્રીતમ",
        "transliteration": "Eji Navroz no din sohāmaṇo\nĀvyo re prītam",
        "english": "Beautiful is the day of Navroz — beloved, you have arrived. Set one calm intention; the year will hold it.",
        "theme": "remembrance",
    },
    {
        "id": "eji_īmān_kā_dīpak",
        "title": "Eji Īmān Kā Dīpak",
        "pir": "Pir Shams",
        "gujarati": "એ જી ઈમાન કા દીપક\nદિલ માહિ બળે",
        "transliteration": "Eji īmān kā dīpak\nDil māhī bale",
        "english": "The lamp of faith burns inside the heart. Tend to it — gently, without showing off — and it will last the night.",
        "theme": "light",
    },
    {
        "id": "eji_seva_karo_re_bhāī",
        "title": "Eji Seva Karo Re Bhāī",
        "pir": "Pir Hasan Kabirdin",
        "gujarati": "એ જી સેવા કરો રે ભાઈ\nનિરમલ ભાવ થી",
        "transliteration": "Eji seva karo re bhāī\nNirmal bhāv thī",
        "english": "Serve, my friend — with a clean heart. Not for credit, not for praise. Just because the world is gentler when you do.",
        "theme": "service",
    },
    {
        "id": "eji_man_re_chalo",
        "title": "Eji Man Re Chālo",
        "pir": "Pir Sadardin",
        "gujarati": "એ જી મન રે ચાલો\nમૂળ મંજિલ રાહ",
        "transliteration": "Eji man re chālo\nMūl manzil rāh",
        "english": "Heart, walk on — the path back to the source is open. The road is quiet; you are not alone.",
        "theme": "journey",
    },
    {
        "id": "eji_satgur_milyā",
        "title": "Eji Satgur Milyā",
        "pir": "Pir Shams",
        "gujarati": "એ જી સતગુર મિલ્યા\nભવ સાગર પાર",
        "transliteration": "Eji satgur milyā\nBhav sāgar pār",
        "english": "I have met the true guide — and across the ocean of life, I can finally rest a moment.",
        "theme": "surrender",
    },
    {
        "id": "eji_aakhā_jāmā_māhī",
        "title": "Eji Ākhā Jāmā Māhī",
        "pir": "Pir Hasan Kabirdin",
        "gujarati": "એ જી આખા જમા માહી\nનૂર સોહામણો",
        "transliteration": "Eji ākhā jāmā māhī\nNūr sohāmaṇo",
        "english": "Within the whole jamat — a beautiful light is shining. Look around this hall; every face is part of it.",
        "theme": "light",
    },
    {
        "id": "eji_chalo_chalo_re_man",
        "title": "Eji Chālo Chālo Re Man",
        "pir": "Pir Sadardin",
        "gujarati": "એ જી ચાલો ચાલો રે મન\nરાહ ગુરુ નો",
        "transliteration": "Eji chālo chālo re man\nRāh guru no",
        "english": "Come on, come on, my heart — the guide's path is waiting. Take the first step before the courage cools.",
        "theme": "journey",
    },
    {
        "id": "eji_prabhu_tum_dīpak",
        "title": "Eji Prabhu Tum Dīpak",
        "pir": "Pir Shams",
        "gujarati": "એ જી પ્રભુ તુમ દીપક\nહું પતંગ",
        "transliteration": "Eji prabhu tum dīpak\nHun patang",
        "english": "Beloved, you are the flame and I am the moth — drawn always to the warmth, even when it costs me everything.",
        "theme": "love",
    },
]

# Each Dua: id, title, situation (when to recite), arabic, transliteration, english, source ("traditional" / "personal")
DUA: list[dict] = [
    {
        "id": "morning_open_heart",
        "title": "Morning · An Open Heart",
        "situation": "When you wake up",
        "arabic": "اللَّهُمَّ افْتَحْ لِي قَلْبِي",
        "transliteration": "Allāhumma iftaḥ lī qalbī",
        "english": "O Lord, please open my heart today. Whatever I meet, let me meet it gently.",
        "source": "personal",
    },
    {
        "id": "morning_intention",
        "title": "Morning · One Intention",
        "situation": "Before stepping out",
        "arabic": "اللَّهُمَّ اجْعَلْ يَوْمِي خَيْرًا لِي",
        "transliteration": "Allāhumma ijʿal yawmī khayran lī",
        "english": "Lord, make today good for me — and through me, for one other soul I meet.",
        "source": "personal",
    },
    {
        "id": "gratitude_simple",
        "title": "Gratitude · For This Moment",
        "situation": "After a meal, before sleep, or any pause",
        "arabic": "الْحَمْدُ لِلَّهِ",
        "transliteration": "Al-ḥamdu lillāh",
        "english": "All praise belongs to the One. Thank you for this breath, this meal, this body.",
        "source": "traditional",
    },
    {
        "id": "anxiety_breathing",
        "title": "Anxiety · A Slow Breath",
        "situation": "When the chest is tight",
        "arabic": "حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
        "transliteration": "Ḥasbunā Allāhu wa niʿma al-wakīl",
        "english": "God is enough for me, and the best to rely on. I let go of the parts I cannot hold.",
        "source": "traditional",
    },
    {
        "id": "healing_self",
        "title": "Healing · For My Body",
        "situation": "When unwell",
        "arabic": "اللَّهُمَّ اشْفِ شِفَاءً لَا يُغَادِرُ سَقَمًا",
        "transliteration": "Allāhumma ishfi shifāʾan lā yughādiru saqamā",
        "english": "Lord, please heal me a healing that leaves no illness behind. Be patient with my body.",
        "source": "traditional",
    },
    {
        "id": "healing_other",
        "title": "Healing · For Someone You Love",
        "situation": "When someone you love is unwell",
        "arabic": "اللَّهُمَّ اشْفِ مَنْ أُحِبُّ",
        "transliteration": "Allāhumma ishfi man uḥibb",
        "english": "Lord, please heal the one I love. Hold them gently tonight.",
        "source": "personal",
    },
    {
        "id": "before_sleep",
        "title": "Before Sleep · Letting Go",
        "situation": "Lying in bed",
        "arabic": "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
        "transliteration": "Bismika Allāhumma amūtu wa aḥyā",
        "english": "In your name I rest, and in your name I will wake. Whatever I have left undone, I trust to you tonight.",
        "source": "traditional",
    },
    {
        "id": "after_difficult",
        "title": "After a Hard Day",
        "situation": "When the day has been heavy",
        "arabic": "اللَّهُمَّ اجْعَلْ هَذَا الْيَوْمَ بَرْكَةً",
        "transliteration": "Allāhumma ijʿal hādhā al-yawma barakah",
        "english": "Lord, please find one blessing in this hard day. Even a small one. Show me, please.",
        "source": "personal",
    },
    {
        "id": "for_parents",
        "title": "For My Parents",
        "situation": "When you think of them",
        "arabic": "رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا",
        "transliteration": "Rabbi irḥamhumā kamā rabbayānī ṣaghīrā",
        "english": "Lord, be merciful to my parents as they raised me when I was small. Soften the years for them.",
        "source": "traditional",
    },
    {
        "id": "forgiveness",
        "title": "Forgiveness · For Today",
        "situation": "When you've been short with someone",
        "arabic": "أَسْتَغْفِرُ اللَّهَ",
        "transliteration": "Astaghfirullāh",
        "english": "I seek your forgiveness. I was small today — help me try again tomorrow.",
        "source": "traditional",
    },
    {
        "id": "travel",
        "title": "Travel · A Safe Journey",
        "situation": "Before a trip",
        "arabic": "اللَّهُمَّ بَلِّغْنَا سَالِمِينَ",
        "transliteration": "Allāhumma balligh-nā sālimīn",
        "english": "Lord, please carry us safely to where we're going — and back, gently.",
        "source": "personal",
    },
    {
        "id": "before_meal",
        "title": "Before a Meal",
        "situation": "Sitting down to eat",
        "arabic": "بِسْمِ اللَّهِ",
        "transliteration": "Bismillāh",
        "english": "In the name of the One. Thank you for the hands that made this — and for the soil, the rain, the work.",
        "source": "traditional",
    },
    {
        "id": "noor_in_chest",
        "title": "Noor · Light in My Chest",
        "situation": "Any quiet moment",
        "arabic": "اللَّهُمَّ اجْعَلْ فِي قَلْبِي نُورًا",
        "transliteration": "Allāhumma ijʿal fī qalbī nūrā",
        "english": "Lord, please place a small light in my heart. Even when the day is overcast, let me feel it.",
        "source": "traditional",
    },
    {
        "id": "guidance_path",
        "title": "Guidance · For This Path",
        "situation": "When the next step is unclear",
        "arabic": "اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ",
        "transliteration": "Ihdinā aṣ-ṣirāṭa al-mustaqīm",
        "english": "Lord, please guide me along the calm and steady path. When I lose my footing, set me back gently.",
        "source": "traditional",
    },
    {
        "id": "patience",
        "title": "Patience · A Long Trial",
        "situation": "When something will not pass quickly",
        "arabic": "إِنَّا لِلَّهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ",
        "transliteration": "Innā lillāhi wa innā ilayhi rājiʿūn",
        "english": "From God we come, and to God we return. This too is part of the journey home.",
        "source": "traditional",
    },
    {
        "id": "joy",
        "title": "Joy · A Small Delight",
        "situation": "When something has gone well",
        "arabic": "اللَّهُمَّ بَارِكْ",
        "transliteration": "Allāhumma bārik",
        "english": "Lord, please bless this moment. Help me hold it long enough to be truly grateful.",
        "source": "personal",
    },
    {
        "id": "before_conversation",
        "title": "Before a Hard Conversation",
        "situation": "Before saying something difficult",
        "arabic": "رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي",
        "transliteration": "Rabbi ishraḥ lī ṣadrī wa yassir lī amrī",
        "english": "Lord, please expand my chest, ease my task, and let my words land with kindness.",
        "source": "traditional",
    },
    {
        "id": "for_children",
        "title": "For My Children",
        "situation": "When you watch them sleep",
        "arabic": "اللَّهُمَّ بَارِكْ لَنَا فِي ذُرِّيَّتِنَا",
        "transliteration": "Allāhumma bārik lanā fī dhurriyyatinā",
        "english": "Lord, please bless our children. Keep them safe, keep them curious, keep them kind.",
        "source": "personal",
    },
    {
        "id": "evening_review",
        "title": "Evening · One Soft Review",
        "situation": "Before reflection",
        "arabic": "اللَّهُمَّ تَوَفَّنِي إِذَا كَانَتِ الْوَفَاةُ خَيْرًا لِي",
        "transliteration": "Allāhumma tawaffanī idhā kānat al-wafātu khayran lī",
        "english": "Lord, take me when going home is best for me. Until then, let me live this day with gentle attention.",
        "source": "traditional",
    },
    {
        "id": "for_community",
        "title": "For the Jamat",
        "situation": "When you think of the global community",
        "arabic": "اللَّهُمَّ احْفَظْ جَمَاعَتَنَا",
        "transliteration": "Allāhumma iḥfaẓ jamāʿatanā",
        "english": "Lord, please protect our jamat — every corner of the world. Soften our edges, deepen our care.",
        "source": "personal",
    },
]

# Family/ECDC — short reflective parenting prompts by age stage.
# Source: distilled from public-domain ECDC frameworks + Ismaili emphasis on
# pluralism, listening, and gentle parenting. Not clinical advice.
FAMILY_CORNER: list[dict] = [
    {
        "id": "infant_eye",
        "stage": "infant",   # 0-2
        "stage_label": "Infant · 0–2 yrs",
        "title": "An Unhurried Gaze",
        "prompt": "Sit with your baby. Look — really look — for one full minute. No phone, no song. Just your eyes and theirs. Notice what arrives in your chest.",
        "duration_min": 1,
    },
    {
        "id": "infant_name",
        "stage": "infant",
        "stage_label": "Infant · 0–2 yrs",
        "title": "Say Their Name Softly",
        "prompt": "Throughout today, say your child's name in the softest voice you can manage. Watch how they orient to it.",
        "duration_min": 5,
    },
    {
        "id": "infant_skin",
        "stage": "infant",
        "stage_label": "Infant · 0–2 yrs",
        "title": "Skin to Skin",
        "prompt": "For ten quiet minutes, hold your baby against your chest. Their heart will slow to match yours.",
        "duration_min": 10,
    },
    {
        "id": "toddler_choices",
        "stage": "toddler",  # 2-4
        "stage_label": "Toddler · 2–4 yrs",
        "title": "Two Small Choices",
        "prompt": "Offer your toddler two choices today instead of one instruction. \"Red cup or blue cup?\" The smallest agency builds the largest trust.",
        "duration_min": 3,
    },
    {
        "id": "toddler_emotion",
        "stage": "toddler",
        "stage_label": "Toddler · 2–4 yrs",
        "title": "Name the Feeling",
        "prompt": "When your toddler melts down, kneel to their height and say the feeling: \"You're frustrated. That's hard.\" Don't fix. Just name. Then sit with them.",
        "duration_min": 5,
    },
    {
        "id": "toddler_routine",
        "stage": "toddler",
        "stage_label": "Toddler · 2–4 yrs",
        "title": "One Sacred Routine",
        "prompt": "Pick one small ritual — a morning kiss, an evening lullaby, a particular hug at bedtime. Do it every day for a week. They will remember it for life.",
        "duration_min": 2,
    },
    {
        "id": "early_curiosity",
        "stage": "early",    # 4-7
        "stage_label": "Early childhood · 4–7 yrs",
        "title": "Honour One Question",
        "prompt": "Children at this age ask 'why?' hundreds of times. Pick one question today and answer it like it's the most important thing you'll do. Sit. Explain. Let them ask the next 'why'.",
        "duration_min": 8,
    },
    {
        "id": "early_storytime",
        "stage": "early",
        "stage_label": "Early childhood · 4–7 yrs",
        "title": "A Story Without a Lesson",
        "prompt": "Read a book at bedtime — not to teach a moral, just for the joy of words. Let them turn the pages. Don't rush.",
        "duration_min": 15,
    },
    {
        "id": "early_pluralism",
        "stage": "early",
        "stage_label": "Early childhood · 4–7 yrs",
        "title": "A Gentle First Pluralism",
        "prompt": "Tell your child about a friend or neighbour from a different faith or background. Use one calm sentence: 'Some people pray standing, some sitting, some quiet — all the prayers are heard.'",
        "duration_min": 4,
    },
    {
        "id": "middle_listening",
        "stage": "middle",   # 7-11
        "stage_label": "Middle childhood · 7–11 yrs",
        "title": "Three Quiet Minutes",
        "prompt": "Ask: 'How was your day?' Then wait. Don't fill the silence. Children of this age need permission to start. Three minutes of patience can unlock everything.",
        "duration_min": 3,
    },
    {
        "id": "middle_seva",
        "stage": "middle",
        "stage_label": "Middle childhood · 7–11 yrs",
        "title": "A Small Seva Together",
        "prompt": "Pick one small act of service — washing a neighbour's plate, sweeping a hallway, leaving a kind note. Do it side by side. No explanation needed.",
        "duration_min": 20,
    },
    {
        "id": "middle_emotion",
        "stage": "middle",
        "stage_label": "Middle childhood · 7–11 yrs",
        "title": "When They're Upset, Don't Fix",
        "prompt": "When your child is angry or sad, resist the urge to solve. Say: 'That sounds really hard. I'm here.' Stay. The lesson is that they are not alone in difficulty.",
        "duration_min": 10,
    },
    {
        "id": "adolescent_trust",
        "stage": "adolescent", # 11-15
        "stage_label": "Adolescent · 11–15 yrs",
        "title": "One Question, No Follow-up",
        "prompt": "Ask one curious question about their world today — a song, a meme, a friend. Don't interrogate. Listen. Tomorrow, ask again. Trust accumulates in small drops.",
        "duration_min": 5,
    },
    {
        "id": "adolescent_identity",
        "stage": "adolescent",
        "stage_label": "Adolescent · 11–15 yrs",
        "title": "Hold Identity Loosely",
        "prompt": "Your teen is becoming. Some days they will look like you; other days, very much not. Let them try on identities. The thread that matters — kindness — is the one you've been weaving for years.",
        "duration_min": 0,
    },
    {
        "id": "teen_phone",
        "stage": "teen",     # 15-18
        "stage_label": "Teen · 15–18 yrs",
        "title": "Phones Down at Dinner",
        "prompt": "One meal this week — no phones at the table. Yours included. The first 5 minutes may be awkward. Stay. The next 25 are the gift.",
        "duration_min": 30,
    },
    {
        "id": "teen_struggle",
        "stage": "teen",
        "stage_label": "Teen · 15–18 yrs",
        "title": "If They're Struggling",
        "prompt": "Teens often signal struggle by withdrawing, not asking. If you sense it: knock gently. Sit on the edge of the bed. Don't lecture. Say: 'I'm here. No agenda. Just here.'",
        "duration_min": 15,
    },
    {
        "id": "all_repair",
        "stage": "all",
        "stage_label": "Any age",
        "title": "Repair After Loss of Temper",
        "prompt": "You will lose your patience. Every parent does. Repair is the most powerful parenting move. Say: 'I shouted earlier. I was tired and that was not your fault. I'm sorry.' Then let it be.",
        "duration_min": 3,
    },
    {
        "id": "all_blessing",
        "stage": "all",
        "stage_label": "Any age",
        "title": "A Quiet Blessing at Night",
        "prompt": "After your child is asleep, sit by them for a moment. Whisper one gentle wish for them — your hope for who they become. They will not hear it. But you will.",
        "duration_min": 2,
    },
]
