/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpiritualRouteImport } from './routes/spiritual'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as ReflectRouteImport } from './routes/reflect'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated.moderation'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated.join'
import { Route as AuthenticatedAdminModeratorsRouteImport } from './routes/_authenticated.admin.moderators'

const SpiritualRoute = SpiritualRouteImport.update({
  id: '/spiritual',
  path: '/spiritual',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectRoute = ReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminModeratorsRoute =
  AuthenticatedAdminModeratorsRouteImport.update({
    id: '/admin/moderators',
    path: '/admin/moderators',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRoute
  '/events': typeof EventsRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reflect': typeof ReflectRoute
  '/reminders': typeof RemindersRoute
  '/report': typeof ReportRoute
  '/spiritual': typeof SpiritualRoute
  '/join': typeof AuthenticatedJoinRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/admin/moderators': typeof AuthenticatedAdminModeratorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/communities': typeof CommunitiesRoute
  '/events': typeof EventsRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reflect': typeof ReflectRoute
  '/reminders': typeof RemindersRoute
  '/report': typeof ReportRoute
  '/spiritual': typeof SpiritualRoute
  '/join': typeof AuthenticatedJoinRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/admin/moderators': typeof AuthenticatedAdminModeratorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/communities': typeof CommunitiesRoute
  '/events': typeof EventsRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reflect': typeof ReflectRoute
  '/reminders': typeof RemindersRoute
  '/report': typeof ReportRoute
  '/spiritual': typeof SpiritualRoute
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/_authenticated/admin/moderators': typeof AuthenticatedAdminModeratorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/communities'
    | '/events'
    | '/guidelines'
    | '/login'
    | '/profile'
    | '/reflect'
    | '/reminders'
    | '/report'
    | '/spiritual'
    | '/join'
    | '/moderation'
    | '/reports'
    | '/invite/$code'
    | '/admin/moderators'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/communities'
    | '/events'
    | '/guidelines'
    | '/login'
    | '/profile'
    | '/reflect'
    | '/reminders'
    | '/report'
    | '/spiritual'
    | '/join'
    | '/moderation'
    | '/reports'
    | '/invite/$code'
    | '/admin/moderators'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/communities'
    | '/events'
    | '/guidelines'
    | '/login'
    | '/profile'
    | '/reflect'
    | '/reminders'
    | '/report'
    | '/spiritual'
    | '/_authenticated/join'
    | '/_authenticated/moderation'
    | '/_authenticated/reports'
    | '/invite/$code'
    | '/_authenticated/admin/moderators'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CommunitiesRoute: typeof CommunitiesRoute
  EventsRoute: typeof EventsRoute
  GuidelinesRoute: typeof GuidelinesRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReflectRoute: typeof ReflectRoute
  RemindersRoute: typeof RemindersRoute
  ReportRoute: typeof ReportRoute
  SpiritualRoute: typeof SpiritualRoute
  InviteCodeRoute: typeof InviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spiritual': {
      id: '/spiritual'
      path: '/spiritual'
      fullPath: '/spiritual'
      preLoaderRoute: typeof SpiritualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflect': {
      id: '/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof ReflectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/moderators': {
      id: '/_authenticated/admin/moderators'
      path: '/admin/moderators'
      fullPath: '/admin/moderators'
      preLoaderRoute: typeof AuthenticatedAdminModeratorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedAdminModeratorsRoute: typeof AuthenticatedAdminModeratorsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedAdminModeratorsRoute: AuthenticatedAdminModeratorsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CommunitiesRoute: CommunitiesRoute,
  EventsRoute: EventsRoute,
  GuidelinesRoute: GuidelinesRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReflectRoute: ReflectRoute,
  RemindersRoute: RemindersRoute,
  ReportRoute: ReportRoute,
  SpiritualRoute: SpiritualRoute,
  InviteCodeRoute: InviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
